version: '3.8'

services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - database
    volumes:
      - ./backend/:/usr/src/backend/

  database:
    image: postgres:13.0-alpine
    env_file:
      - ./.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    build: ./frontend
    ports:
      - 1337:80
    depends_on:
      - backend
    volumes:
      - static_volume:/home/backend/web/staticfiles

volumes:
  postgres_data:
  static_volume:
  media_volume: